spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    host: 172.16.126.194
    port: 5672
    username: guest
    password: guest
  redis:
    host: 127.0.0.1
    port: 6379
  jpa:
    show-sql: true
girl: 20
server:
  port: 8085
zuul:
  routes:
    myOrder1:
      serviceId: order
      path: /myOrder/**
    myOO:
      serviceId: order
      path: /myOO/**
    myP:
      serviceId: product
      path: /myP/**
  sensitive-headers:
